#!/usr/bin/env php
<?php
// Source https://github.com/RWOverdijk/AssetManager/blob/master/coverage-checker.php
// Modified for colorized output by Evan

$inputFile = $argv[1];
$percentage = min(100, max(0, (int) $argv[2]));

if (!file_exists($inputFile)) {
    throw new InvalidArgumentException('Invalid input file provided');
}

if (!$percentage) {
    throw new InvalidArgumentException('An integer checked percentage must be given as second parameter');
}

$xml = new SimpleXMLElement(file_get_contents($inputFile));
/* @var $metrics SimpleXMLElement[] */
$metrics = $xml->xpath('//metrics');

$totalElements = 0;
$checkedElements = 0;

foreach ($metrics as $metric) {
    $totalElements   += (int) $metric['elements'];
    $checkedElements += (int) $metric['coveredelements'];
}

$coverage = round(($checkedElements / $totalElements) * 100);

echo PHP_EOL;

if ($coverage < $percentage) {
    echo "\x1b[37;41m";
    echo "Code coverage is {$coverage}%, which is below the accepted {$percentage}%";
    echo "\x1b[0m" . PHP_EOL . PHP_EOL;
    exit(1);
}

echo "\x1b[30;42m";
echo "Code coverage is {$coverage}% - OK!";
echo "\x1b[0m" . PHP_EOL . PHP_EOL;
