#!/usr/bin/env bash
output=$(php php-cs-fixer.phar fix -v --no-interaction --dry-run --level=all src/)
echo ""
if [[ $output ]]; then
    while read -r line
    do
        echo -e "\e[37;41m$line\e[00m"
    done <<< "$output"
    false
else
    echo -e "\e[30;42mCoding standards are OK\e[0m"
fi
