#!/usr/bin/env bash
output=$(php php-cs-fixer.phar fix --no-interaction --dry-run --level=psr2 .)
echo ""
length=$(echo "$output" | wc -l)
#php-cs-fixer always output the line that give the time and the amount of memory consumed, so we need to ignore it.
if [[ $length -gt 1 ]]; then
    while read -r line
    do
        echo -e "\e[37;41m$line\e[00m"
    done <<< "$output"
    false
else
    echo -e "\e[30;42mCoding standards are OK\e[0m"
fi
