language: php

php:
  - 5.3
  - 5.4

before_install:
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit -c test/phpunit.xml
 - ./test/coverage-checker test/clover.xml 95
 - output=$(php php-cs-fixer.phar fix -v --no-interaction --dry-run --level=all .); echo ""; if [[ $output ]]; then while read -r line; do echo -e "\e[37;41m$line\e[00m"; done <<< "$output"; false; else echo -e "\e[30;42mCoding standards are OK\e[0m"; fi;
