language: php

php:
  - 5.3
  - 5.4

before_install:
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit -c test/phpunit.xml
 - ./test/coverage-checker test/clover.xml 95
 - output=$(php php-cs-fixer.phar fix -v --no-interaction --dry-run --level=all .); if [[ $output ]]; then while read -r line; do echo -e "\e[1;31m$line\e[0m"; done <<< "$output"; false; fi;
