language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
 - wget -q http://get.sensiolabs.org/php-cs-fixer.phar

script:
 - phpunit -c test/phpunit.xml
 - ./test/coverage-checker test/clover.xml 100
 - ./test/cs-checker
