<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sslurp\Module'             => __DIR__ . '/Module.php',
    'Sslurp\Sslurp'             => __DIR__ . '/src/Sslurp/Sslurp.php',
    'Sslurp\AbstractCaRootData' => __DIR__ . '/src/Sslurp/AbstractCaRootData.php',
    'Sslurp\MozillaCertData'    => __DIR__ . '/src/Sslurp/MozillaCertData.php',
    'Sslurp\CaRootPemBundle'    => __DIR__ . '/src/Sslurp/CaRootPemBundle.php',
    'Sslurp\X509Certificate'    => __DIR__ . '/src/Sslurp/X509Certificate.php',
);
