<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sslurp\Module'              => __DIR__ . '/Module.php',
    'Sslurp\RootCaBundleBuilder' => __DIR__ . '/src/Sslurp/RootCaBundleBuilder.php',
);
